# -*- coding: utf-8 -*-
"""Question no 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jw9RepH_3d2vguGegrnmaoAZCKik-7GE
"""

total = int(input())
final_dict = {}
for i in range(total):
  try:
    student = [input()]
    student_list = student[0].split(' ')
    final_dict[student_list[1]]= student_list[2]
  except:
    print('You input wronged info')
sortednames= dict( sorted(final_dict.items(), key=lambda x: x[0].lower()) )
df = sorted(sortednames.items(), key = lambda x: x[1], reverse=True)
for i in range(len(df)):
  print(df[i][0])